/* Persistent, browser-only language and appearance preferences. */
(function (root) {
  'use strict';

  const DEFAULTS = Object.freeze({ language: 'en', theme: 'pink' });
  const LANGUAGES = Object.freeze([
    ['en', 'English'], ['hi', 'हिन्दी'], ['ta', 'தமிழ்'], ['te', 'తెలుగు'],
    ['ml', 'മലയാളം'], ['kn', 'ಕನ್ನಡ'], ['mr', 'मराठी']
  ]);
  const THEMES = Object.freeze(['pink', 'dark']);
  const english = {
    'nav.regimen': 'Regimen overview', 'nav.demographic': 'Demographic lens', 'nav.pathway': 'Pathway inspector', 'nav.substitution': 'Substitution engine', 'nav.review': 'Review & export', 'nav.settings': 'Settings',
    'shell.workspace': 'Workspace / Demo case 004', 'shell.synthetic': 'Synthetic data', 'shell.reset': 'Reset demo', 'shell.resetTitle': 'Reset the demo?', 'shell.resetBody': 'This restores the sample medicines and patient context.', 'shell.confirmReset': 'Reset demo', 'shell.addMedicine': '+ Add a medicine', 'shell.statusSaved': 'Settings saved.',
    'settings.title': 'Settings', 'settings.subtitle': 'Personalise the workspace without changing your clinical case.', 'settings.language': 'Language', 'settings.languageHint': 'Choose the language used throughout the interface.', 'settings.appearance': 'Appearance', 'settings.appearanceHint': 'Use a darker workspace after sunset or in low light.', 'settings.apply': 'Apply settings', 'settings.active': 'Active',
    'theme.pink': 'Pink', 'theme.dark': 'Dark mode',
    'workspace.selectedPair': 'Selected pair: {{pair}}', 'workspace.currentMedicines': 'Current medicines', 'workspace.interactionMatrix': 'Interaction matrix', 'workspace.view3d': 'View 3D map', 'workspace.findAlternatives': 'Find alternatives', 'workspace.inspectPathway': 'Inspect pathway ↗', 'workspace.medicineAdded': 'Medicine added. Regimen updated.', 'workspace.medicineRemoved': 'Medicine removed. Regimen updated.', 'workspace.addMedicineTitle': 'Add a medicine', 'workspace.medicineName': 'Medicine name', 'workspace.doseNotes': 'Dose / notes (optional)', 'workspace.add': 'Add medicine',
    'common.age': 'Age', 'common.sexGender': 'Sex / Gender', 'common.female': 'Female', 'common.male': 'Male', 'common.unknown': 'Unknown / not recorded', 'common.update': 'Update comparison →', 'common.loading': 'Loading…', 'common.noData': 'No supported estimate', 'common.back': 'Back to workspace'
  };
  const translations = {
    en: english,
    hi: {
      'nav.regimen':'दवा योजना', 'nav.demographic':'जनसांख्यिकीय दृश्य', 'nav.pathway':'पथवे निरीक्षक', 'nav.substitution':'विकल्प इंजन', 'nav.review':'समीक्षा और निर्यात', 'nav.settings':'सेटिंग्स',
      'shell.workspace':'कार्यस्थान / डेमो केस 004', 'shell.synthetic':'कृत्रिम डेटा', 'shell.reset':'डेमो रीसेट करें', 'shell.resetTitle':'डेमो रीसेट करें?', 'shell.resetBody':'यह नमूना दवाएँ और रोगी संदर्भ बहाल करता है।', 'shell.confirmReset':'डेमो रीसेट करें', 'shell.addMedicine':'+ दवा जोड़ें', 'shell.statusSaved':'सेटिंग्स सहेजी गईं।',
      'settings.title':'सेटिंग्स', 'settings.subtitle':'अपने क्लिनिकल केस को बदले बिना कार्यस्थान को वैयक्तिकृत करें।', 'settings.language':'भाषा', 'settings.languageHint':'इंटरफ़ेस में प्रयुक्त भाषा चुनें।', 'settings.appearance':'रूप', 'settings.appearanceHint':'कार्यस्थान के लिए रंग पैलेट चुनें।', 'settings.apply':'सेटिंग्स लागू करें', 'settings.active':'सक्रिय',
      'theme.pink':'गुलाबी', 'theme.lavender':'लैवेंडर', 'theme.mint':'मिंट', 'theme.blue':'नीला', 'workspace.selectedPair':'चयनित जोड़ी: {{pair}}', 'workspace.currentMedicines':'वर्तमान दवाएँ', 'workspace.interactionMatrix':'इंटरैक्शन मैट्रिक्स', 'workspace.view3d':'3D मानचित्र देखें', 'workspace.findAlternatives':'विकल्प खोजें', 'workspace.inspectPathway':'पथवे देखें ↗', 'workspace.medicineAdded':'दवा जोड़ी गई। योजना अपडेट हुई।', 'workspace.medicineRemoved':'दवा हटाई गई। योजना अपडेट हुई।', 'workspace.addMedicineTitle':'दवा जोड़ें', 'workspace.medicineName':'दवा का नाम', 'workspace.doseNotes':'खुराक / नोट्स (वैकल्पिक)', 'workspace.add':'दवा जोड़ें', 'common.age':'आयु', 'common.sexGender':'लिंग', 'common.female':'महिला', 'common.male':'पुरुष', 'common.unknown':'अज्ञात / दर्ज नहीं', 'common.update':'तुलना अपडेट करें →', 'common.loading':'लोड हो रहा है…', 'common.noData':'कोई समर्थित अनुमान नहीं', 'common.back':'कार्यस्थान पर वापस जाएँ'
    },
    ta: {
      'nav.regimen':'மருந்துத் திட்டம்', 'nav.demographic':'மக்கள்தொகை பார்வை', 'nav.pathway':'பாதை ஆய்வி', 'nav.substitution':'மாற்று இயந்திரம்', 'nav.review':'மதிப்பாய்வு மற்றும் ஏற்றுமதி', 'nav.settings':'அமைப்புகள்', 'shell.workspace':'பணியிடம் / டெமோ வழக்கு 004', 'shell.synthetic':'செயற்கை தரவு', 'shell.reset':'டெமோவை மீட்டமை', 'shell.resetTitle':'டெமோவை மீட்டமைக்கவா?', 'shell.resetBody':'இது மாதிரி மருந்துகள் மற்றும் நோயாளர் சூழலை மீட்டமைக்கும்.', 'shell.confirmReset':'டெமோவை மீட்டமை', 'shell.addMedicine':'+ மருந்தைச் சேர்', 'shell.statusSaved':'அமைப்புகள் சேமிக்கப்பட்டன.', 'settings.title':'அமைப்புகள்', 'settings.subtitle':'உங்கள் மருத்துவ வழக்கை மாற்றாமல் பணியிடத்தைத் தனிப்பயனாக்குங்கள்.', 'settings.language':'மொழி', 'settings.languageHint':'இடைமுகம் முழுவதும் பயன்படுத்தும் மொழியைத் தேர்ந்தெடுக்கவும்.', 'settings.appearance':'தோற்றம்', 'settings.appearanceHint':'பணியிடத்திற்கான வண்ணத் தொகுப்பைத் தேர்ந்தெடுக்கவும்.', 'settings.apply':'அமைப்புகளைப் பயன்படுத்து', 'settings.active':'செயலில்', 'theme.pink':'இளஞ்சிவப்பு', 'theme.lavender':'லாவெண்டர்', 'theme.mint':'மின்ட்', 'theme.blue':'நீலம்', 'workspace.selectedPair':'தேர்ந்தெடுத்த ஜோடி: {{pair}}', 'workspace.currentMedicines':'தற்போதைய மருந்துகள்', 'workspace.interactionMatrix':'தொடர்பு அணி', 'workspace.view3d':'3D வரைபடத்தைக் காண்க', 'workspace.findAlternatives':'மாற்றுகளைக் காண்க', 'workspace.inspectPathway':'பாதையைப் பார்வையிடுக ↗', 'workspace.medicineAdded':'மருந்து சேர்க்கப்பட்டது. திட்டம் புதுப்பிக்கப்பட்டது.', 'workspace.medicineRemoved':'மருந்து அகற்றப்பட்டது. திட்டம் புதுப்பிக்கப்பட்டது.', 'workspace.addMedicineTitle':'மருந்தைச் சேர்', 'workspace.medicineName':'மருந்தின் பெயர்', 'workspace.doseNotes':'அளவு / குறிப்புகள் (விருப்பம்)', 'workspace.add':'மருந்தைச் சேர்', 'common.age':'வயது', 'common.sexGender':'பாலினம்', 'common.female':'பெண்', 'common.male':'ஆண்', 'common.unknown':'தெரியவில்லை / பதிவு இல்லை', 'common.update':'ஒப்பீட்டைப் புதுப்பி →', 'common.loading':'ஏற்றுகிறது…', 'common.noData':'ஆதரிக்கப்படும் மதிப்பீடு இல்லை', 'common.back':'பணியிடத்திற்குத் திரும்பு'
    },
    te: { 'nav.regimen':'ఔషధ ప్రణాళిక', 'nav.demographic':'జనాభా దృశ్యం', 'nav.pathway':'మార్గ పరిశీలకుడు', 'nav.substitution':'ప్రత్యామ్నాయ యంత్రం', 'nav.review':'సమీక్ష మరియు ఎగుమతి', 'nav.settings':'సెట్టింగ్‌లు', 'shell.workspace':'వర్క్‌స్పేస్ / డెమో కేసు 004', 'shell.synthetic':'కృత్రిమ డేటా', 'shell.reset':'డెమో రీసెట్', 'shell.resetTitle':'డెమోను రీసెట్ చేయాలా?', 'shell.resetBody':'ఇది నమూనా మందులు మరియు రోగి సందర్భాన్ని పునరుద్ధరిస్తుంది.', 'shell.confirmReset':'డెమో రీసెట్', 'shell.addMedicine':'+ మందు జోడించండి', 'shell.statusSaved':'సెట్టింగ్‌లు సేవ్ చేయబడ్డాయి.', 'settings.title':'సెట్టింగ్‌లు', 'settings.subtitle':'మీ క్లినికల్ కేసును మార్చకుండా వర్క్‌స్పేస్‌ను వ్యక్తిగతీకరించండి.', 'settings.language':'భాష', 'settings.languageHint':'ఇంటర్‌ఫేస్‌లో ఉపయోగించే భాషను ఎంచుకోండి.', 'settings.appearance':'రూపం', 'settings.appearanceHint':'వర్క్‌స్పేస్ కోసం రంగుల పాలెట్‌ను ఎంచుకోండి.', 'settings.apply':'సెట్టింగ్‌లను వర్తించు', 'settings.active':'సక్రియం', 'theme.pink':'పింక్', 'theme.lavender':'లావెండర్', 'theme.mint':'మింట్', 'theme.blue':'నీలం', 'workspace.selectedPair':'ఎంచుకున్న జంట: {{pair}}', 'workspace.currentMedicines':'ప్రస్తుత మందులు', 'workspace.interactionMatrix':'పరస్పర చర్య మ్యాట్రిక్స్', 'workspace.view3d':'3D మ్యాప్ చూడండి', 'workspace.findAlternatives':'ప్రత్యామ్నాయాలు కనుగొనండి', 'workspace.inspectPathway':'మార్గాన్ని పరిశీలించండి ↗', 'workspace.medicineAdded':'మందు జోడించబడింది. ప్రణాళిక నవీకరించబడింది.', 'workspace.medicineRemoved':'మందు తొలగించబడింది. ప్రణాళిక నవీకరించబడింది.', 'workspace.addMedicineTitle':'మందు జోడించండి', 'workspace.medicineName':'మందు పేరు', 'workspace.doseNotes':'మోతాదు / గమనికలు (ఐచ్ఛికం)', 'workspace.add':'మందు జోడించండి', 'common.age':'వయస్సు', 'common.sexGender':'లింగం', 'common.female':'స్త్రీ', 'common.male':'పురుషుడు', 'common.unknown':'తెలియదు / నమోదు కాలేదు', 'common.update':'పోలికను నవీకరించు →', 'common.loading':'లోడ్ అవుతోంది…', 'common.noData':'మద్దతు ఉన్న అంచనా లేదు', 'common.back':'వర్క్‌స్పేస్‌కు తిరిగి వెళ్ళు' },
    ml: { 'nav.regimen':'മരുന്ന് പദ്ധതി', 'nav.demographic':'ജനസംഖ്യാപരമായ കാഴ്ച', 'nav.pathway':'പാത പരിശോധകൻ', 'nav.substitution':'ബദൽ എഞ്ചിൻ', 'nav.review':'അവലോകനവും കയറ്റുമതിയും', 'nav.settings':'ക്രമീകരണങ്ങൾ', 'shell.workspace':'വർക്ക്‌സ്‌പേസ് / ഡെമോ കേസ് 004', 'shell.synthetic':'സിന്തറ്റിക് ഡാറ്റ', 'shell.reset':'ഡെമോ പുനഃസജ്ജമാക്കുക', 'shell.resetTitle':'ഡെമോ പുനഃസജ്ജമാക്കണോ?', 'shell.resetBody':'ഇത് മാതൃകാ മരുന്നുകളും രോഗിയുടെ സന്ദർഭവും പുനഃസ്ഥാപിക്കുന്നു.', 'shell.confirmReset':'ഡെമോ പുനഃസജ്ജമാക്കുക', 'shell.addMedicine':'+ മരുന്ന് ചേർക്കുക', 'shell.statusSaved':'ക്രമീകരണങ്ങൾ സംരക്ഷിച്ചു.', 'settings.title':'ക്രമീകരണങ്ങൾ', 'settings.subtitle':'നിങ്ങളുടെ ക്ലിനിക്കൽ കേസ് മാറ്റാതെ വർക്ക്‌സ്‌പേസ് വ്യക്തിഗതമാക്കുക.', 'settings.language':'ഭാഷ', 'settings.languageHint':'ഇന്റർഫേസിൽ ഉപയോഗിക്കേണ്ട ഭാഷ തിരഞ്ഞെടുക്കുക.', 'settings.appearance':'രൂപം', 'settings.appearanceHint':'വർക്ക്‌സ്‌പേസിനായി ഒരു വർണ്ണ പാലറ്റ് തിരഞ്ഞെടുക്കുക.', 'settings.apply':'ക്രമീകരണങ്ങൾ പ്രയോഗിക്കുക', 'settings.active':'സജീവം', 'theme.pink':'പിങ്ക്', 'theme.lavender':'ലാവെൻഡർ', 'theme.mint':'മിന്റ്', 'theme.blue':'നീല', 'workspace.selectedPair':'തിരഞ്ഞെടുത്ത ജോഡി: {{pair}}', 'workspace.currentMedicines':'നിലവിലെ മരുന്നുകൾ', 'workspace.interactionMatrix':'ഇടപെടൽ മാട്രിക്സ്', 'workspace.view3d':'3D മാപ്പ് കാണുക', 'workspace.findAlternatives':'ബദലുകൾ കണ്ടെത്തുക', 'workspace.inspectPathway':'പാത പരിശോധിക്കുക ↗', 'workspace.medicineAdded':'മരുന്ന് ചേർത്തു. പദ്ധതി പുതുക്കി.', 'workspace.medicineRemoved':'മരുന്ന് നീക്കി. പദ്ധതി പുതുക്കി.', 'workspace.addMedicineTitle':'മരുന്ന് ചേർക്കുക', 'workspace.medicineName':'മരുന്നിന്റെ പേര്', 'workspace.doseNotes':'ഡോസ് / കുറിപ്പുകൾ (ഐച്ഛികം)', 'workspace.add':'മരുന്ന് ചേർക്കുക', 'common.age':'പ്രായം', 'common.sexGender':'ലിംഗം', 'common.female':'സ്ത്രീ', 'common.male':'പുരുഷൻ', 'common.unknown':'അജ്ഞാതം / രേഖപ്പെടുത്തിയിട്ടില്ല', 'common.update':'താരതമ്യം പുതുക്കുക →', 'common.loading':'ലോഡ് ചെയ്യുന്നു…', 'common.noData':'പിന്തുണയുള്ള അനുമാനം ഇല്ല', 'common.back':'വർക്ക്‌സ്‌പേസിലേക്ക് മടങ്ങുക' },
    kn: { 'nav.regimen':'ಔಷಧ ಯೋಜನೆ', 'nav.demographic':'ಜನಸಾಂಖ್ಯಿಕ ನೋಟ', 'nav.pathway':'ಮಾರ್ಗ ಪರಿಶೀಲಕ', 'nav.substitution':'ಪರ್ಯಾಯ ಎಂಜಿನ್', 'nav.review':'ವಿಮರ್ಶೆ ಮತ್ತು ರಫ್ತು', 'nav.settings':'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', 'shell.workspace':'ಕಾರ್ಯಕ್ಷೇತ್ರ / ಡೆಮೊ ಪ್ರಕರಣ 004', 'shell.synthetic':'ಸಿಂಥೆಟಿಕ್ ಡೇಟಾ', 'shell.reset':'ಡೆಮೊ ಮರುಹೊಂದಿಸಿ', 'shell.resetTitle':'ಡೆಮೊ ಮರುಹೊಂದಿಸಬೇಕೇ?', 'shell.resetBody':'ಇದು ಮಾದರಿ ಔಷಧಿಗಳು ಮತ್ತು ರೋಗಿಯ ಸಂದರ್ಭವನ್ನು ಮರುಸ್ಥಾಪಿಸುತ್ತದೆ.', 'shell.confirmReset':'ಡೆಮೊ ಮರುಹೊಂದಿಸಿ', 'shell.addMedicine':'+ ಔಷಧಿ ಸೇರಿಸಿ', 'shell.statusSaved':'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗಿದೆ.', 'settings.title':'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', 'settings.subtitle':'ನಿಮ್ಮ ಕ್ಲಿನಿಕಲ್ ಪ್ರಕರಣವನ್ನು ಬದಲಾಯಿಸದೆ ಕಾರ್ಯಕ್ಷೇತ್ರವನ್ನು ವೈಯಕ್ತಿಕಗೊಳಿಸಿ.', 'settings.language':'ಭಾಷೆ', 'settings.languageHint':'ಇಂಟರ್‌ಫೇಸ್‌ನಲ್ಲಿ ಬಳಸುವ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.', 'settings.appearance':'ನೋಟ', 'settings.appearanceHint':'ಕಾರ್ಯಕ್ಷೇತ್ರಕ್ಕೆ ಬಣ್ಣದ ಪ್ಯಾಲೆಟ್ ಆಯ್ಕೆಮಾಡಿ.', 'settings.apply':'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಅನ್ವಯಿಸಿ', 'settings.active':'ಸಕ್ರಿಯ', 'theme.pink':'ಗುಲಾಬಿ', 'theme.lavender':'ಲ್ಯಾವೆಂಡರ್', 'theme.mint':'ಮಿಂಟ್', 'theme.blue':'ನೀಲಿ', 'workspace.selectedPair':'ಆಯ್ಕೆ ಮಾಡಿದ ಜೋಡಿ: {{pair}}', 'workspace.currentMedicines':'ಪ್ರಸ್ತುತ ಔಷಧಿಗಳು', 'workspace.interactionMatrix':'ಪರಸ್ಪರ ಕ್ರಿಯೆ ಮ್ಯಾಟ್ರಿಕ್ಸ್', 'workspace.view3d':'3D ನಕ್ಷೆ ನೋಡಿ', 'workspace.findAlternatives':'ಪರ್ಯಾಯಗಳನ್ನು ಹುಡುಕಿ', 'workspace.inspectPathway':'ಮಾರ್ಗ ಪರಿಶೀಲಿಸಿ ↗', 'workspace.medicineAdded':'ಔಷಧಿ ಸೇರಿಸಲಾಗಿದೆ. ಯೋಜನೆ ನವೀಕರಿಸಲಾಗಿದೆ.', 'workspace.medicineRemoved':'ಔಷಧಿ ತೆಗೆದುಹಾಕಲಾಗಿದೆ. ಯೋಜನೆ ನವೀಕರಿಸಲಾಗಿದೆ.', 'workspace.addMedicineTitle':'ಔಷಧಿ ಸೇರಿಸಿ', 'workspace.medicineName':'ಔಷಧಿಯ ಹೆಸರು', 'workspace.doseNotes':'ಡೋಸ್ / ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)', 'workspace.add':'ಔಷಧಿ ಸೇರಿಸಿ', 'common.age':'ವಯಸ್ಸು', 'common.sexGender':'ಲಿಂಗ', 'common.female':'ಮಹಿಳೆ', 'common.male':'ಪುರುಷ', 'common.unknown':'ತಿಳಿದಿಲ್ಲ / ದಾಖಲಾಗಿಲ್ಲ', 'common.update':'ಹೋಲಿಕೆಯನ್ನು ನವೀಕರಿಸಿ →', 'common.loading':'ಲೋಡ್ ಆಗುತ್ತಿದೆ…', 'common.noData':'ಬೆಂಬಲಿತ ಅಂದಾಜು ಇಲ್ಲ', 'common.back':'ಕಾರ್ಯಕ್ಷೇತ್ರಕ್ಕೆ ಹಿಂತಿರುಗಿ' },
    mr: { 'nav.regimen':'औषध योजना', 'nav.demographic':'लोकसंख्या दृश्य', 'nav.pathway':'मार्ग निरीक्षक', 'nav.substitution':'पर्याय इंजिन', 'nav.review':'पुनरावलोकन आणि निर्यात', 'nav.settings':'सेटिंग्ज', 'shell.workspace':'कार्यस्थळ / डेमो प्रकरण 004', 'shell.synthetic':'कृत्रिम डेटा', 'shell.reset':'डेमो रीसेट करा', 'shell.resetTitle':'डेमो रीसेट करायचा?', 'shell.resetBody':'हे नमुना औषधे आणि रुग्ण संदर्भ पुनर्संचयित करते.', 'shell.confirmReset':'डेमो रीसेट करा', 'shell.addMedicine':'+ औषध जोडा', 'shell.statusSaved':'सेटिंग्ज जतन केल्या.', 'settings.title':'सेटिंग्ज', 'settings.subtitle':'तुमचा क्लिनिकल केस न बदलता कार्यस्थळ वैयक्तिकृत करा.', 'settings.language':'भाषा', 'settings.languageHint':'इंटरफेसमध्ये वापरायची भाषा निवडा.', 'settings.appearance':'देखावा', 'settings.appearanceHint':'कार्यस्थळासाठी रंग पॅलेट निवडा.', 'settings.apply':'सेटिंग्ज लागू करा', 'settings.active':'सक्रिय', 'theme.pink':'गुलाबी', 'theme.lavender':'लॅव्हेंडर', 'theme.mint':'मिंट', 'theme.blue':'निळा', 'workspace.selectedPair':'निवडलेली जोडी: {{pair}}', 'workspace.currentMedicines':'सध्याची औषधे', 'workspace.interactionMatrix':'परस्परसंवाद मॅट्रिक्स', 'workspace.view3d':'3D नकाशा पहा', 'workspace.findAlternatives':'पर्याय शोधा', 'workspace.inspectPathway':'मार्ग तपासा ↗', 'workspace.medicineAdded':'औषध जोडले. योजना अद्ययावत झाली.', 'workspace.medicineRemoved':'औषध काढले. योजना अद्ययावत झाली.', 'workspace.addMedicineTitle':'औषध जोडा', 'workspace.medicineName':'औषधाचे नाव', 'workspace.doseNotes':'डोस / टिपा (ऐच्छिक)', 'workspace.add':'औषध जोडा', 'common.age':'वय', 'common.sexGender':'लिंग', 'common.female':'महिला', 'common.male':'पुरुष', 'common.unknown':'अज्ञात / नोंद नाही', 'common.update':'तुलना अद्ययावत करा →', 'common.loading':'लोड होत आहे…', 'common.noData':'समर्थित अंदाज नाही', 'common.back':'कार्यस्थळावर परत जा' }
  };
  translations.te = { ...english, ...translations.te };
  translations.ml = { ...english, ...translations.ml };
  translations.kn = { ...english, ...translations.kn };
  translations.mr = { ...english, ...translations.mr };
  translations.hi = { ...english, ...translations.hi };
  translations.ta = { ...english, ...translations.ta };
  const languageCode = { en: 'en', hi: 'hi', ta: 'ta', te: 'te', ml: 'ml', kn: 'kn', mr: 'mr' };
  const phraseKeys = Object.fromEntries(Object.entries(english).map(([key, phrase]) => [phrase, key]));
  const normalize = value => ({ language: LANGUAGES.some(([id]) => id === value?.language) ? value.language : DEFAULTS.language, theme: THEMES.includes(value?.theme) ? value.theme : DEFAULTS.theme });

  function createPreferences(storage) {
    const storageKey = 'pharmagnn-preferences-v1';
    let state = { ...DEFAULTS };
    try { state = normalize(JSON.parse(storage?.getItem(storageKey) || 'null')); } catch {}
    const t = (key, variables = {}) => String((translations[state.language] || english)[key] ?? english[key] ?? key).replace(/{{(\w+)}}/g, (_, name) => variables[name] ?? '');
    const api = {
      get: () => ({ ...state }), languages: () => LANGUAGES.map(([id, label]) => ({ id, label })), themes: () => [...THEMES],
      save: value => { state = normalize(value); try { storage?.setItem(storageKey, JSON.stringify(state)); } catch {} return { ...state }; },
      t,
      apply: document => { if (!document) return; document.documentElement.dataset.theme = state.theme; document.documentElement.lang = languageCode[state.language]; },
      translateDocument: document => {
        if (!document) return;
        document.querySelectorAll('[data-i18n]').forEach(node => { node.textContent = t(node.dataset.i18n); });
        document.querySelectorAll('[data-i18n-aria-label]').forEach(node => { node.setAttribute('aria-label', t(node.dataset.i18nAriaLabel)); });
        document.querySelectorAll('[data-i18n-title]').forEach(node => { node.title = t(node.dataset.i18nTitle); });
        const translateText = scope => {
          const walker = document.createTreeWalker(scope, NodeFilter.SHOW_TEXT);
          const nodes = []; let node;
          while ((node = walker.nextNode())) nodes.push(node);
          nodes.forEach(textNode => {
            const value = textNode.nodeValue.trim(); const key = phraseKeys[value];
            if (key) textNode.nodeValue = textNode.nodeValue.replace(value, t(key));
          });
        };
        translateText(document.body || document);
        if (!document.documentElement.dataset.i18nObserver) {
          document.documentElement.dataset.i18nObserver = 'true';
          new MutationObserver(records => records.forEach(record => record.addedNodes.forEach(node => {
            if (node.nodeType === Node.ELEMENT_NODE) translateText(node);
            if (node.nodeType === Node.TEXT_NODE) { const value = node.nodeValue.trim(); if (phraseKeys[value]) node.nodeValue = node.nodeValue.replace(value, t(phraseKeys[value])); }
          }))).observe(document.body, { childList: true, subtree: true });
        }
      }
    };
    return api;
  }
  const api = { createPreferences, DEFAULTS, LANGUAGES, THEMES };
  if (typeof module !== 'undefined') module.exports = api;
  if (typeof window !== 'undefined') {
    let storage; try { storage = window.localStorage; } catch {}
    root.PharmaPreferences = createPreferences(storage);
    root.PharmaPreferences.apply(document);
  }
})(globalThis);
