renderWorkspaceShell('Substitution engine');UI.text('pageHeading','A considered alternative starts here.');UI.text('pageSubhead','Compare candidates against the indication and the entire regimen.');
UI.text('rankedNote','Ranked by simulated pairwise score ↓');UI.text('candidateBanner','Candidates are hypothetical UI examples. Lower predicted scores do not establish clinical safety or interchangeability.');
const candidates=PharmaStore.getCandidates();let selected=candidates[0];
const e=UI.escape;
document.getElementById('replaceCard').innerHTML='<div class="replace-block"><span class="context-label">REPLACE IN DRAFT</span><span class="replace-drug-name">'+(candidates.length?'Amitriptyline':'No supported alternative fixture')+'</span></div><div class="replace-block"><span class="context-label">THERAPEUTIC INTENT</span><div class="field-box">Depression · demo scenario</div></div><div class="replace-tags"><span class="pill pill-muted">Preserve indication</span><span class="pill pill-muted">Review contraindications</span></div>';
function render(){document.getElementById('candidateList').innerHTML=candidates.map((c,i)=>'<li><button type="button" class="candidate-row '+(c.id===selected.id?'selected':'')+'" data-candidate="'+c.id+'" aria-pressed="'+(c.id===selected.id)+'"><span class="candidate-rank">0'+(i+1)+'</span><span class="candidate-info"><span class="candidate-name">'+e(c.name)+'</span><span class="candidate-subtitle">Hypothetical therapeutic alternative</span><span class="candidate-badge '+(i?'badge-warn':'badge-good')+'">'+e(c.badge)+'</span></span><span class="candidate-score-block"><span class="candidate-score">'+c.score+'</span><span class="candidate-score-max">/ 100</span></span><span class="candidate-delta-block"><span class="candidate-delta">'+(c.score-82)+'</span><span class="candidate-delta-label">points</span></span></button></li>').join('')||'<li class="empty-state">No candidate fixtures for the selected pair. <a href="workspace.html">Return to the regimen</a> to select amitriptyline and citalopram, or reset the demo.</li>';
  const card=document.getElementById('candidateDetailCard');if(!selected){card.innerHTML='<h2>Evidence is needed</h2><p>Alternatives are not invented for unsupported medicines.</p>';return;}const count=PharmaStore.getState().medicines.length;
  card.innerHTML='<h2 class="candidate-detail-name">'+e(selected.name)+'</h2><p class="ws-card-note">Review before simulating</p><div class="detail-rows">'+[['Indication match','Demo match'],['Contraindications','Not evaluated'],['Dose equivalence','Requires review'],['Regimen coverage',count*(count-1)/2+' pairwise checks']].map(([a,b])=>'<div class="detail-row"><span class="detail-term">'+a+'</span><span class="detail-value">'+b+'</span></div>').join('')+'</div><button class="btn btn-primary ws-btn-block" id="simulateBtn">Simulate this candidate →</button>';document.getElementById('simulateBtn').onclick=()=>{PharmaStore.simulate(selected.id);UI.go('regimen-simulation');};
}
document.getElementById('candidateList').onclick=event=>{const b=event.target.closest('[data-candidate]');if(b){selected=candidates.find(c=>c.id===b.dataset.candidate);render();}};render();
